[package]
name = "rustyrocks"
version = "0.1.0"
authors = ["Wendell Smith <wackywendell@gmail.com>"]
edition = "2018"

[dependencies]
rocksdb = "0.14.0"
serde = "1.0.110" # Probably not needed anymore?
bincode = "1.2.1"
failure = "0.1.8"
