[package]
authors = ["Wendell Smith <wackywendell@gmail.com>"]
edition = "2018"
name = "rustyrocks"
version = "0.1.0"

[dependencies]
bincode = "1.3"
failure = "0.1.8"
rocksdb = "0.15"

[dev-dependencies]
serde = {version = "1.0", features = ["derive"]}
