[package]
authors = ["Wendell Smith <wackywendell@gmail.com>"]
edition = "2018"
name = "rustyrocks"
version = "0.1.0"

[dependencies]
bincode = "1.3.1" 
failure = "0.1.5" 
rocksdb = "0.15.0" 
serde = "1.0.92" # Probably not needed anymore?
